murkyManagerApp:
  name: manager-app
  namespace: dev
  replicas: 1
  containerPort: 3000
  image:
    repository: kvait/murky-manager-app
    tag: tru
  service:
    name: manager-app-service
    type: ClusterIP
    port: 80
    targetPort: 3000

murkyApi:
  name: murky-api
  namespace: dev
  replicas: 1
  containerPort: 3001
  image:
    repository: kvait/murky-manager-server-app
    tag: dev
  service:
    name: murky-api-service
    type: ClusterIP
    port: 3001
    targetPort: 3001

postgres:
  name: postgres-db
  namespace: dev
  replicas: 1
  containerPort: 5432
  image:
    repository: postgres
    tag: "13"
  service:
    name: postgres-service
    type: ClusterIP
    port: 5432
    targetPort: 5432
  volumes:
    storage:
      name: postgres-storage
      pvcName: postgres-pvc
      pvName: postgres-pv
      mountPath: /var/lib/postgresql/data
      size: 2Gi

ingress:
  name: ingress-app
  namespace: dev
  host: dev.cursetheweb.online
  