apiVersion: apps/v1
kind: Deployment
metadata:
  name: lens-api-deployment
  labels:
    app: lens-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lens-api
  template:
    metadata:
      labels:
        app: lens-api
    spec:
      initContainers:
      - name: init-mydb
        image: busybox
        command: ['sh', '-c', 'until nslookup postgres-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
      containers:
        - name: lens-api
          image: kvait/murky-manager-server-app:dev
          ports:
            - containerPort: 3001
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-pass
            - name: DATABASE_URL
              value: "postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres-service:5432/mydb?schema=public"
