apiVersion: apps/v1
kind: Deployment
metadata:
  name: lens-api-deployment
  labels:
    app: lens-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lens-api
  template:
    metadata:
      labels:
        app: lens-api
    spec:
      initContainers:
      - name: init-mydb
        image: busybox
        command: ['sh', '-c', 'until nslookup postgres-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
      containers:
        - name: lens-api
          image: kvait/lens-api:1
          ports:
            - containerPort: 3001
