apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.murkyApi.service.name }}
  namespace: {{ .Values.murkyApi.namespace }}
spec:
  type: {{ .Values.murkyApi.service.type }}
  ports:
    - port: {{ .Values.murkyApi.service.port }}
      targetPort: {{ .Values.murkyApi.service.targetPort }}
  selector:
    app: {{ .Values.murkyApi.name }}
