apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.murkyManagerApp.name }}
  namespace: {{ .Values.murkyManagerApp.namespace }}
spec:
  replicas: {{ .Values.murkyManagerApp.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.murkyManagerApp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.murkyManagerApp.name }}
    spec:
      nodeSelector:
        role: frontend
      containers:
        - name: {{ .Values.murkyManagerApp.name }}
          image: "{{ .Values.murkyManagerApp.image.repository }}:{{ .Values.murkyManagerApp.image.tag }}"
          ports:
            - containerPort: {{ .Values.murkyManagerApp.containerPort }}
          imagePullPolicy: Always
