apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.volumes.storage.pvcName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.volumes.storage.size }}
