apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgres.volumes.storage.pvName }}
  namespace: {{ .Values.postgres.namespace }}
spec:
  capacity:
    storage: {{ .Values.postgres.volumes.storage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres