apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.host }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /api/lenses
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.murkyApi.service.name }}
            port:
              number: {{ .Values.murkyApi.service.port }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.murkyManagerApp.service.name }}
            port:
              number: {{ .Values.murkyManagerApp.service.port }}
